Give the script a much needed makeover

diff --git a/replace-gh-labels b/replace-gh-labels
--- a/replace-gh-labels
+++ b/replace-gh-labels
@@ -3,256 +3,385 @@
 # vim: syntax=sh
 # code: language=shellscript
 
-# === opts =================================================================== #
+# Copyright (c) 2024 Michael Federczuk
 
-case "$1" in
-	'--help'|'-h')
-		echo "usage: $0 <repo_name>"
+#region preamble
+
+case "$-" in
+	(*'i'*)
+		if \command test -n "${BASH_VERSION-}"; then
+			# using `eval` here in case a non-Bash shell tries to parse this branch even if the condition is false
+			\command eval "\\command printf '%s: ' \"\${BASH_SOURCE[0]}\" >&2"
+		fi
+
+		\command printf 'script was called interactively\n' >&2
+		return 124
+		;;
+esac
+
+set -o errexit
+set -o nounset
+
+# enabling POSIX-compliant behavior for GNU programs
+export POSIXLY_CORRECT=yes POSIX_ME_HARDER=yes
+
+if [ -z "${BASH_VERSION-}" ]; then
+	if [ "${0#/}" = "$0" ]; then
+		argv0="$0"
+	else
+		argv0="$(basename -- "$0" && printf x)"
+		argv0="${argv0%"$(printf '\nx')"}"
+	fi
+	readonly argv0
+
+	printf '%s: GNU Bash is required for this script\n' "$argv0" >&2
+	exit 1
+fi
+
+declare argv0
+if [[ ! "$0" =~ ^'/' ]]; then
+	argv0="$0"
+else
+	argv0="$(basename -- "$0" && printf x)"
+	argv0="${argv0%$'\nx'}"
+fi
+readonly argv0
+
+#endregion
+
+function curl() {
+	if ! command -v curl > '/dev/null'; then
+		printf '%s: curl: program missing\n' "$argv0" >&2
+		return 27
+	fi
+
+	command curl "$@"
+}
+
+function jq() {
+	if ! command -v jq > '/dev/null'; then
+		printf '%s: jq: program missing\n' "$argv0" >&2
+		return 27
+	fi
+
+	command jq "$@"
+}
+
+#region processing the arguments
+
+case "${1-}" in
+	('--help'|'-h')
+		printf 'usage: %s <repo_name>\n' "$argv0"
 		exit
 		;;
-	'--version'|'-V')
-		echo "replace-gh-labels v1.0.0-rc01
-Copyright (C) 2020 Michael Federczuk
+	('--version'|'-V')
+		printf 'replace-gh-labels v1.0.0-rc01
+Copyright (C) 2024 Michael Federczuk
 License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>
 This is free software: you are free to change and redistribute it.
 There is NO WARRANTY, to the extent permitted by law.
 
-Written by Michael Federczuk."
+Written by Michael Federczuk.\n'
 		exit
 		;;
 esac
 
-# ============================================================================ #
-# === repo name ============================================================== #
+declare repo_name
 
-readonly repo_name_patern='^[A-Za-z0-9_-]+$'
-
-if (($# == 0)); then
-	echo "$0: missing argument: <repo_name>" >&2
-	exit 4
-elif [ -z "$1" ]; then
-	echo "$0: argument may not be empty" >&2
-	exit 9
-elif [[ ! "$1" =~ $repo_name_patern ]]; then
-	echo "$0: $1: does not match: /${repo_name_patern//\//\\\/}/" >&2
-	exit 12
-fi
-
-readonly repo_name="$1"
-
-# ============================================================================ #
-
-readonly root_dir="$(realpath "$(dirname "$0")")"
-
-# === user =================================================================== #
-
-readonly user_file_path="$root_dir/user"
-readonly user_file_rel_path="$(realpath --relative-to=. "$user_file_path")"
-
-if [ ! -e "$user_file_path" ]; then
-	echo "$0: $user_file_rel_path: no such file" >&2
-	exit 24
-elif [ ! -f "$user_file_path" ]; then
-	echo "$0: $user_file_rel_path: not a file" >&2
-	exit 26
-elif [ ! -r "$user_file_path" ]; then
-	echo "$0: $user_file_rel_path: permission denied" >&2
-	exit 77
-fi
-
-readonly user="$(< "$user_file_path")"
-
-readonly user_pattern='^[A-Za-z0-9_-]+$'
-if [[ ! "$user" =~ $user_pattern ]]; then
-	echo "$0: $user_file_rel_path: $user: does not match: /${user_pattern//\//\\\/}/"
-	exit 79
-fi
-
-# ============================================================================ #
-# === check github connection ================================================ #
-
-if ! ping 'github.com' -c 1 -w 7 > '/dev/null'; then
-	echo "$0: no network connection to github.com"
-	exit 29
-fi
-
-# ============================================================================ #
-# === check if repository exists ============================================= #
-
-case "$(curl -s \
-		        -w '%{http_code}' \
-		        -o '/dev/null' \
-		        -H 'Accept: application/vnd.github.v3+json' \
-		        "https://api.github.com/repos/$user/$repo_name")" in
-	2*)
-		# repo exists
+case $# in
+	(0)
+		printf '%s: missing argument: <repo_name>\n' "$argv0" >&2
+		exit 4
 		;;
-	404)
-		echo "$0: $user/$repo_name: GitHub repository does not exist"
-		exit 48
+	(1)
+		if [ -z "$1" ]; then
+			printf '%s: argument must not be empty\n' "$argv0" >&2
+			exit 9
+		fi
+
+		readonly repo_name_pattern='^[A-Za-z0-9_-]+$'
+		if [[ ! "$1" =~ $repo_name_pattern ]]; then
+			printf '%s: %s: does not match: /%s/\n' "$argv0" "$1" "${repo_name_pattern//\//\\\/}" >&2
+			exit 12
+		fi
+
+		repo_name="$1"
 		;;
-	4*)
-		echo "$0: unknown client error"
-		exit 125
-		;;
-	5*)
-		echo "$0: unknown server error"
-		exit 125
-		;;
-	*)
-		echo "$0: unknown error"
-		exit 125
+	(*)
+		printf '%s: too many arguments: %d\n' "$argv0" $(($# - 1)) >&2
+		exit 4
 		;;
 esac
 
-# ============================================================================ #
-# === access token =========================================================== #
+readonly repo_name
 
-readonly access_token_file_path="$root_dir/access_token"
-readonly access_token_file_rel_path="$(realpath --relative-to=. "$access_token_file_path")"
+#endregion
 
-if [ ! -e "$access_token_file_path" ]; then
-	echo "$0: $access_token_file_rel_path: no such file" >&2
+declare root_dir_pathname
+root_dir_pathname="$(dirname -- "$0" && printf x)"
+root_dir_pathname="${root_dir_pathname%$'\nx'}"
+readonly root_dir_pathname
+
+#region reading the username
+
+declare username_file_pathname
+username_file_pathname="$root_dir_pathname/user"
+readonly username_file_pathname
+
+if [ ! -e "$username_file_pathname" ]; then
+	printf '%s: %s: no such file\n' "$argv0" "$username_file_pathname" >&2
 	exit 24
-elif [ ! -f "$access_token_file_path" ]; then
-	echo "$0: $access_token_file_rel_path: not a file" >&2
+fi
+
+if [ ! -f "$username_file_pathname" ]; then
+	printf '%s: %s: not a file\n' "$argv0" "$username_file_pathname" >&2
 	exit 26
-elif [ ! -r "$access_token_file_path" ]; then
-	echo "$0: $access_token_file_rel_path: permission denied" >&2
+fi
+
+if [ ! -r "$username_file_pathname" ]; then
+	printf '%s: %s: permission denied: read permission missing\n' "$argv0" "$username_file_pathname" >&2
 	exit 77
 fi
 
-readonly access_token="$(< "$access_token_file_path")"
+declare username
+username="$(< "$username_file_pathname")"
+readonly username
+
+readonly username_pattern='^[A-Za-z0-9_-]+$'
+if [[ ! "$username" =~ $username_pattern ]]; then
+	printf '%s: %s: %s: does not match: /%s/\n' "$argv0" "$username_file_pathname" "$username" "${username_pattern//\//\\\/}" >&2
+	exit 79
+fi
+
+#endregion
+
+#region reading the access token
+
+declare access_token_file_pathname
+access_token_file_pathname="$root_dir_pathname/access_token"
+readonly access_token_file_pathname
+
+if [ ! -e "$access_token_file_pathname" ]; then
+	printf '%s: %s: no such file\n' "$argv0" "$access_token_file_pathname" >&2
+	exit 24
+fi
+
+if [ ! -f "$access_token_file_pathname" ]; then
+	printf '%s: %s: not a file\n' "$argv0" "$access_token_file_pathname" >&2
+	exit 26
+fi
+
+if [ ! -r "$access_token_file_pathname" ]; then
+	printf '%s: %s: permission denied: read permission missing\n' "$argv0" "$access_token_file_pathname" >&2
+	exit 77
+fi
+
+declare access_token
+access_token="$(< "$access_token_file_pathname")"
+readonly access_token
 
 if [ -z "$access_token" ]; then
-	echo "$0: $access_token_file_rel_path: access token is empty" >&2
+	printf '%s: %s: access token is empty\n' "$argv0" "$access_token_file_pathname" >&2
 	exit 80
 fi
 
-# ============================================================================ #
+#endregion
 
-declare exc
+#region reading the new labels
 
-# === new labels ============================================================= #
+declare new_labels_json_file_pathname
+new_labels_json_file_pathname="$root_dir_pathname/github_issue_labels.json"
+readonly new_labels_json_file_pathname
 
-readonly new_labels_json_file="$root_dir/github_issue_labels.json"
-readonly new_labels_json_file_rel_path="$(realpath --relative-to=. "$new_labels_json_file")"
-
-if [ ! -e "$new_labels_json_file" ]; then
-	echo "$0: $new_labels_json_file_rel_path: no such file" >&2
+if [ ! -e "$new_labels_json_file_pathname" ]; then
+	printf '%s: %s: no such file\n' "$argv0" "$new_labels_json_file_pathname" >&2
 	exit 24
-elif [ ! -f "$new_labels_json_file" ]; then
-	echo "$0: $new_labels_json_file_rel_path: not a file" >&2
+fi
+
+if [ ! -f "$new_labels_json_file_pathname" ]; then
+	printf '%s: %s: not a file\n' "$argv0" "$new_labels_json_file_pathname" >&2
 	exit 26
-elif [ ! -r "$new_labels_json_file" ]; then
-	echo "$0: $new_labels_json_file_rel_path: permission denied" >&2
+fi
+
+if [ ! -r "$new_labels_json_file_pathname" ]; then
+	printf '%s: %s: permission denied: read permission missing\n' "$argv0" "$new_labels_json_file_pathname" >&2
 	exit 77
 fi
 
 declare new_labels_json
-new_labels_json="$(jq -c 'map({name, description: (if .description == null then "" else .description end), color: (if .color == null then "000000" else .color end)})' "$new_labels_json_file" | sed s/'null'/'""'/g)"
-exc=$?
-
-if ((exc != 0)); then
-	exit $exc
-fi
+new_labels_json="$(jq -c 'map({
+	name,
+	description: (if .description == null then "" else .description end),
+	color: (if .color == null then "000000" else .color end)
+})' "$new_labels_json_file_pathname")"
 readonly new_labels_json
 
-readonly new_labels_count="$(jq 'length' <<< "$new_labels_json")"
+#endregion
 
-# ============================================================================ #
+#region checking connection to github.com
 
-echo "Repository: $user/$repo_name (https://github.com/$user/$repo_name)"
+if command -v ping > '/dev/null'; then
+	if ! ping -c 2 -w 10 'github.com' > '/dev/null'; then
+		printf '%s: no network connection to github.com\n' "$argv0" >&2
+		exit 29
+	fi
+else
+	printf "Command 'ping' not found; cannot test connection to 'github.com'.\\n" >&2
+fi
 
-# === fetching old labels ==================================================== #
+#endregion
 
-echo
-echo 'Fetching old labels...'
+#region checking if repository exists
+
+declare response_code
+response_code="$(curl --silent --show-error \
+                      --location \
+                      --write-out '%{http_code}' \
+                      --output '/dev/null' \
+                      --user "$username:$access_token" \
+                      --header 'Accept: application/vnd.github.v3+json' \
+                      "https://api.github.com/repos/$username/$repo_name")"
+
+case "$response_code" in
+	(2*)
+		# repo exists
+		;;
+	(404)
+		printf '%s: %s/%s: GitHub repository does not exist\n' "$argv0" "$username" "$repo_name" >&2
+		exit 48
+		;;
+	(*)
+		printf '%s: unknown error (HTTP response code %s)\n' "$argv0" "$response_code" >&2
+		exit 125
+		;;
+esac
+
+unset -v response_code
+
+#endregion
+
+printf 'Using repository %s/%s (https://github.com/%s/%s)\n\n' "$username" "$repo_name" "$username" "$repo_name" >&2
+
+#region fetching old labels
+
+printf 'Fetching old labels...\n' >&2
+
+declare -a old_labels
+old_labels=()
 
 declare old_labels_json
-old_labels_json="$( \
-	curl -s \
-	-u "$user:$access_token" \
-	-H 'Accept: application/vnd.github.v3+json' \
-	"https://api.github.com/repos/$user/$repo_name/labels" \
-)"
-exc=$?
+old_labels_json="$(curl --silent --show-error \
+                        --location \
+                        --user "$username:$access_token" \
+                        --header 'Accept: application/vnd.github.v3+json' \
+                        "https://api.github.com/repos/$username/$repo_name/labels")"
 
-if ((exc != 0)); then
-	echo $exc
-fi
-readonly old_labels_json
+declare -i old_labels_count
+old_labels_count="$(jq 'length' <<< "$old_labels_json")"
 
-readonly old_labels_count="$(jq 'length' <<< "$old_labels_json")"
+declare -i i
 
-declare old_labels=()
 for ((i = 0; i < old_labels_count; ++i)); do
-	old_labels+=("$(jq -r ".[$i].name" <<< "$old_labels_json")")
-done; unset -v i
+	old_labels+=(
+		"$(jq --raw-output ".[$i].name" <<< "$old_labels_json")"
+	)
+done
+
+unset -v i \
+         old_labels_count \
+         old_labels_json
+
 readonly old_labels
 
-# ============================================================================ #
+#endregion
 
-_url_encode() {
-	local -r str="$1"
-	local out=''
+printf '\n' >&2
 
-	local i c cp; for ((i = 0; i < ${#str}; ++i)); do
-		c="${str:i:1}"
-		cp="$(printf '%s' "$c" | hexdump -e '/1 "%02d"')"
+#region deleting old labels
 
-		if [[ "$c" =~ ^[]:?\#@\!\$\&\'\"\(\)*+,\;=\ []$ ]] || ((cp > 127)); then
-			out+="$(printf '%%%02X' "$cp")"
+function percent_encode() {
+	local unencoded_string
+	unencoded_string="$1"
+	readonly unencoded_string
+
+	local bytes
+	bytes="$(printf '%s' "$unencoded_string" | od -v -An -tu1)"
+	readonly bytes
+
+	local encoded_string
+	encoded_string=''
+
+	local -i byte
+	for byte in $bytes; do
+		# <https://datatracker.ietf.org/doc/html/rfc3986#section-2.3>
+		if ((byte >= 65 && byte <= 90)) || # A-Z
+		   ((byte >= 97 && byte <= 122)) || # a-z
+		   ((byte >= 48 && byte <= 57)) || # 0-9
+		   ((byte == 45)) || ((byte == 46)) || # hypen & period
+		   ((byte == 95)) || ((byte == 126)); then # underscore & tilde
+
+			# shellcheck disable=2059
+			encoded_string+="$(printf "\\$(printf '%o' $byte)")"
 		else
-			out+="$c"
+			encoded_string+="%$(printf '%02x' $byte)"
 		fi
-	done; unset -v c i
+	done
 
-	printf '%s' "$out"
+	printf '%s' "$encoded_string"
 }
 
-# === deleting old labels ==================================================== #
-
-echo
-
+declare old_label
 for old_label in "${old_labels[@]}"; do
-	echo "Deleting old label '$old_label'..."
+	printf "Deleting old label '%s'...\\n" "$old_label" >&2
 
-	curl -s \
-		-X DELETE \
-		-u "$user:$access_token" \
-		-H 'Accept: application/vnd.github.v3+json' \
-		"https://api.github.com/repos/$user/$repo_name/labels/$(_url_encode "$old_label")" > '/dev/null'
-	exc=$?
+	declare old_label_percent_encoded
+	old_label_percent_encoded="$(percent_encode "$old_label")"
 
-	if ((exc != 0)); then
-		exit $exc
-	fi
-done; unset -v old_label
+	curl --silent --show-error \
+	     --location \
+	     --output '/dev/null' \
+	     --request DELETE \
+	     --user "$username:$access_token" \
+	     --header 'Accept: application/vnd.github.v3+json' \
+	     "https://api.github.com/repos/$username/$repo_name/labels/$old_label_percent_encoded"
 
-# ============================================================================ #
-# === creating new labels ==================================================== #
+	unset -v old_label_percent_encoded
+done
+unset -v old_label
 
-echo
+#endregion
 
-declare new_label_json; for ((i = 0; i < new_labels_count; ++i)); do
+printf '\n' >&2
+
+#region creating new labels
+
+declare -i new_labels_count
+new_labels_count="$(jq 'length' <<< "$new_labels_json")"
+
+for ((i = 0; i < new_labels_count; ++i)); do
+	declare new_label_json
 	new_label_json="$(jq -cM ".[$i]" <<< "$new_labels_json")"
-	echo "Creating new label '$(jq -rM '.name' <<< "$new_label_json")'..."
 
-	curl -s \
-		-X POST \
-		-u "$user:$access_token" \
-		-H "Accept: application/vnd.github.v3+json" \
-		"https://api.github.com/repos/$user/$repo_name/labels" \
-		-d "$new_label_json" > '/dev/null'
-	exc=$?
+	declare new_label_name
+	new_label_name="$(jq -rM '.name' <<< "$new_label_json")"
 
-	if ((exc != 0)); then
-		exit $exc
-	fi
-done; unset -v new_label_json
+	printf "Creating new label '%s'...\\n" "$new_label_name" >&2
 
-# ============================================================================ #
+	curl --silent --show-error \
+	     --location \
+	     --output '/dev/null' \
+	     --request POST \
+	     --user "$username:$access_token" \
+	     --header "Accept: application/vnd.github.v3+json" \
+	     --data-raw "$new_label_json" \
+	     "https://api.github.com/repos/$username/$repo_name/labels"
 
-echo
-echo "We're done. Everything should be fine!"
+	unset -v new_label_name \
+	         new_label_json
+done
+
+unset -v new_labels_count
+
+#endregion
+
+printf '\nDone.\n' >&2
